spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/pub-sub
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true